name = input("Nhap ho ten: ")
age = input ("Nhap nam sinh: ")
country = input ("Nhap que quan: ")
heigth = input ("Nhap chieu cao: ")
weigth = input ("Nhap can nang: ")
total = input ("Nhap xep loai tot nghiep: ")
print (" ")
print ("*****************************")
print ("***** SO YEU LY LICH ********")
print ("*****************************")
print ("Ho ten: ", name)
print ("Nam sinh:", age)
print ("Que quan:", country)
print ("Chieu cao:", heigth, "m")
print ("Can nang:", weigth, "kg")
print ("Tot nghiep loai:", total)
print ("*****************************")